# Site settings
title: Silicolight
email: contact@silicolight.com
permalink: /:categories/:title.html
description: > # this means to ignore newlines until "baseurl:"
  Un Silicolight est un cache ampoule ou filtre de couleur en silicone pour lampes basse consommation ou LED.
tel: 0961630916

facebook: https://www.facebook.com/Silicolight-119502024889476/
twitter: https://twitter.com/silicolight
youtube: https://www.youtube.com/channel/UCNk8zguchAIcgELv_Pycu5g

baseurl: "/silicolight" # the subpath of your site, e.g. /blog
url: "https://romarr.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

l18n:
  fr:
    profile: "Mon compte"
    cart: "Panier"
    links: "Liens"
    cookies: Cookies
    cookiesurl: cookies-fr
    terms: Conditions
    termsurl: apropos
    contact: Contact
    contacturl: contact
    description: > # this means to ignore newlines until "baseurl:"
      Un Silicolight est un cache ampoule ou filtre de couleur en silicone pour lampes basse consommation ou LED.
  en:
    profile: "Profile"
    cart: "Cart"
    links: "Links"
    cookies: Cookies
    cookiesurl: cookies-en
    terms: Terms
    termsurl: about
    contact: Contact
    contacturl: about
    description: > # this means to ignore newlines until "baseurl:"
      Silicolight is a color silicone cover for low-energy and led lights. Silicolight is made from flexible translucent silicone.

# Gems et extensions
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
exclude:
- Dockerfile

collections_dir: collections

collections:
  produits:
  products:
  blogen:
    output: true
    permalink: /blog/en/:title
  blogfr:
    output: true
    permalink: /blog/fr/:title
  
sass:
  sass_dir: css
  style: compressed