backend:
  name: github
  repo: romarr/silicolight # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://rsoauth.herokuapp.com


media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "produits"
    label: "Produits"
    folder: "collections/_produits"
    create: true
    slug: "{{day}}-{{second}}_{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Id", name: "pid", widget: "string"}
      - {label: "Miniature", name: "thumb", widget: "image"}
      - {label: "Photos", name: "photos", widget: "list", field: {label: Photo, name: photo, widget: image}}
      - {label: "Couleurs", name: "couleurs", widget: "list", required: false}
      - {label: "Poids", name: "poids", widget: "number"}
      - {label: "Prix", name: "prix", widget: "string"}
      - {label: "Dimensions", name: "dims", widget: "string"}